version: 1
disable_existing_loggers: False

iracing_user_id: "898674"

backend_domain: "192.168.178.104"
grpc_port: 9001
http_port: 8080

storage_path: "C:\Temp"

formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    development:
        level: DEBUG
        handlers: [console]
        propagate: no

    staging:
        level: INFO
        handlers: [console]
        propagate: no

    production:
        level: WARNING
        handlers: [console]
        propagate: no

root:
    level: DEBUG
    handlers: [console]
