# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from iracingsetups_client import iracing_pb2 as iracingsetups__client_dot_iracing__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in iracingsetups_client/iracing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class IracingServiceStub(object):
    """IracingService definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNewSession = channel.unary_unary(
                '/iracingsetups.IracingService/SendNewSession',
                request_serializer=iracingsetups__client_dot_iracing__pb2.SendNewSessionRequest.SerializeToString,
                response_deserializer=iracingsetups__client_dot_iracing__pb2.SucessReply.FromString,
                _registered_method=True)
        self.SendCarSetup = channel.unary_unary(
                '/iracingsetups.IracingService/SendCarSetup',
                request_serializer=iracingsetups__client_dot_iracing__pb2.SendCarSetupRequest.SerializeToString,
                response_deserializer=iracingsetups__client_dot_iracing__pb2.SucessReply.FromString,
                _registered_method=True)
        self.SendTelemetry = channel.unary_unary(
                '/iracingsetups.IracingService/SendTelemetry',
                request_serializer=iracingsetups__client_dot_iracing__pb2.SendTelemetryRequest.SerializeToString,
                response_deserializer=iracingsetups__client_dot_iracing__pb2.SucessReply.FromString,
                _registered_method=True)
        self.SendTyreData = channel.unary_unary(
                '/iracingsetups.IracingService/SendTyreData',
                request_serializer=iracingsetups__client_dot_iracing__pb2.SendTyreDataRequest.SerializeToString,
                response_deserializer=iracingsetups__client_dot_iracing__pb2.SucessReply.FromString,
                _registered_method=True)


class IracingServiceServicer(object):
    """IracingService definition
    """

    def SendNewSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCarSetup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTyreData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IracingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNewSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNewSession,
                    request_deserializer=iracingsetups__client_dot_iracing__pb2.SendNewSessionRequest.FromString,
                    response_serializer=iracingsetups__client_dot_iracing__pb2.SucessReply.SerializeToString,
            ),
            'SendCarSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCarSetup,
                    request_deserializer=iracingsetups__client_dot_iracing__pb2.SendCarSetupRequest.FromString,
                    response_serializer=iracingsetups__client_dot_iracing__pb2.SucessReply.SerializeToString,
            ),
            'SendTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTelemetry,
                    request_deserializer=iracingsetups__client_dot_iracing__pb2.SendTelemetryRequest.FromString,
                    response_serializer=iracingsetups__client_dot_iracing__pb2.SucessReply.SerializeToString,
            ),
            'SendTyreData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTyreData,
                    request_deserializer=iracingsetups__client_dot_iracing__pb2.SendTyreDataRequest.FromString,
                    response_serializer=iracingsetups__client_dot_iracing__pb2.SucessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iracingsetups.IracingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iracingsetups.IracingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IracingService(object):
    """IracingService definition
    """

    @staticmethod
    def SendNewSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iracingsetups.IracingService/SendNewSession',
            iracingsetups__client_dot_iracing__pb2.SendNewSessionRequest.SerializeToString,
            iracingsetups__client_dot_iracing__pb2.SucessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCarSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iracingsetups.IracingService/SendCarSetup',
            iracingsetups__client_dot_iracing__pb2.SendCarSetupRequest.SerializeToString,
            iracingsetups__client_dot_iracing__pb2.SucessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iracingsetups.IracingService/SendTelemetry',
            iracingsetups__client_dot_iracing__pb2.SendTelemetryRequest.SerializeToString,
            iracingsetups__client_dot_iracing__pb2.SucessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTyreData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iracingsetups.IracingService/SendTyreData',
            iracingsetups__client_dot_iracing__pb2.SendTyreDataRequest.SerializeToString,
            iracingsetups__client_dot_iracing__pb2.SucessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
